fisher install idkjs/battery
fisher install idkjs/battery_indicator
fisher install idkjs/colortest
fisher install idkjs/confirm
fisher install idkjs/extract
fisher install idkjs/fh
fisher install idkjs/fromhex
fisher install idkjs/git-clc
fisher install idkjs/git-delete-merged-branches
fisher install idkjs/git-kill
fisher install idkjs/git-modified
fisher install idkjs/isdir
fisher install idkjs/isfile
fisher install idkjs/login-shell
fisher install idkjs/reason-language-server
fisher install idkjs/reload-browser
fisher install idkjs/subl
fisher install idkjs/tm
